"""
Inference pool of try-face-rekog application.

Generated by 'elangai generate' using `elangai` 1.1.0.
"""

from elangai import *

@elangai_pool
def inference_pool(ELANGAI_ENV):
    """Inference pool function.

    :param ELANGAI_ENV: elangai environment variable to interact with
    :return: valid dictionary for the output
    """
    ELANGAI_ENV = ELANGAI_ENV['face_640'].predict(ELANGAI_ENV)
    boxes = ELANGAI_ENV['boxes']
    ELANGAI_ENV['face_features'] = list()
    ELANGAI_ENV['img_result'] = ELANGAI_ENV['frame']
    print('[INFO] pool -> boxes shape:', boxes.shape)
    print('[INFO] number of boxes > 0 ...')
    for i in range(boxes.shape[0]):
        ELANGAI_ENV['box'] = boxes[i, :]
        ELANGAI_ENV = ELANGAI_ENV['mobilefacenet'].predict(ELANGAI_ENV)
    return ELANGAI_ENV

