"""
Preparation of try-face-rekog application.

Generated by 'elangai generate' using `elangai` 1.1.0.
"""


from elangai import *


facedet_model = 'face_640.trt' # Only accepts '.trt' or '.tflite'
facedet_label = "face-det.txt" # if not available put an empty string ("")
InferencePool(facedet_model, facedet_label, FP16)

face_recog = "mobilefacenet.trt"
face_label = ""
InferencePool(face_recog, face_label, FP16)
