"""
Main program for techbros-xl-lpr application.

Generated by 'elangai generate' using `elangai` 1.1.0.

Do not edit!
"""

from elangai import *
import app.autoinit


def main():
    app = ElangApp()
    app.run()


if __name__ == '__main__':
    main()
