"""
Inference pool of lpr-elangai-trt application.

Generated by 'elangai generate' using `elangai` 1.1.0.
"""

from elangai import *


@elangai_pool
def inference_pool(ELANGAI_ENV):
    """Inference pool function.

    :param ELANGAI_ENV: elangai environment variable to interact with
    :return: valid dictionary for the output
    """
    ELANGAI_ENV = ELANGAI_ENV['vehicle'].predict(ELANGAI_ENV)
    vehicle_boxes = ELANGAI_ENV['vehicle_boxes']
    # ELANGAI_ENV['licence_num'] = list()
    ELANGAI_ENV['img_result'] = ELANGAI_ENV['frame']
    print('[INFO] pool -> vehicle_boxes shape:', vehicle_boxes.shape)
    # for i in range(vehicle_boxes.shape[0]):
    #     ELANGAI_ENV['box'] = vehicle_boxes[i, :]
    #     ELANGAI_ENV = ELANGAI_ENV['plate'].predict(ELANGAI_ENV)
    return ELANGAI_ENV