"""
Preparation of face-mask-detection application.

Generated by 'elangai generate' using `elangai` 1.1.0.
"""


from elangai import *


model_name = 'face_mask.trt' # Only accepts '.trt' or '.tflite'
label_name = "labels-face-mask.txt" # if not available put an empty string ("")
InferencePool(model_name, label_name, FP16)
