"""
autoinit of disease-classification-elangai application.

Generated by 'elangai generate' using `elangai` 1.1.0.

Do not edit!
"""

import importlib

from elangai import *
import utils


configure_callback(utils)
configure_pool(importlib.import_module('app.pool'))


import app.prepare
