"""
Preparation of disease-classification-elangai application.

Generated by 'elangai generate' using `elangai` 1.1.0.
"""


from elangai import *


model_name = 'disease.tflite' # Only accepts '.trt' or '.tflite'
label_name = "leaf_desease_cls.txt" # if not available put an empty string ("")
InferencePool(model_name, label_name, FP32)
